[2023-03-08T05:00:23.722+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_postgrest_v1.create_postgres_table manual__2023-03-08T05:00:21.719312+00:00 [queued]>
[2023-03-08T05:00:23.749+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_postgrest_v1.create_postgres_table manual__2023-03-08T05:00:21.719312+00:00 [queued]>
[2023-03-08T05:00:23.750+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-08T05:00:23.750+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 6
[2023-03-08T05:00:23.750+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-08T05:00:23.781+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2023-03-08 05:00:21.719312+00:00
[2023-03-08T05:00:23.788+0000] {standard_task_runner.py:55} INFO - Started process 5099 to run task
[2023-03-08T05:00:23.794+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_postgrest_v1', 'create_postgres_table', 'manual__2023-03-08T05:00:21.719312+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres.py', '--cfg-path', '/tmp/tmp5eqpgk7q']
[2023-03-08T05:00:23.798+0000] {standard_task_runner.py:83} INFO - Job 71: Subtask create_postgres_table
[2023-03-08T05:00:23.934+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_postgrest_v1.create_postgres_table manual__2023-03-08T05:00:21.719312+00:00 [running]> on host df4d96e1a045
[2023-03-08T05:00:24.138+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Aditya
AIRFLOW_CTX_DAG_ID=dag_postgrest_v1
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2023-03-08T05:00:21.719312+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-08T05:00:21.719312+00:00
[2023-03-08T05:00:24.139+0000] {sql.py:254} INFO - Executing: 
        create table if not exist (
            dt date,
            dag_id character varying,
            primary key (dt, dag_id)
        )
        
[2023-03-08T05:00:24.159+0000] {base.py:73} INFO - Using connection ID 'postgrest_localhost' for task execution.
[2023-03-08T05:00:24.702+0000] {base.py:73} INFO - Using connection ID 'postgrest_localhost' for task execution.
[2023-03-08T05:00:24.736+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 342, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 144, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "***" to address: Temporary failure in name resolution

[2023-03-08T05:00:24.751+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_postgrest_v1, task_id=create_postgres_table, execution_date=20230308T050021, start_date=20230308T050023, end_date=20230308T050024
[2023-03-08T05:00:24.769+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 71 for task create_postgres_table (could not translate host name "***" to address: Temporary failure in name resolution
; 5099)
[2023-03-08T05:00:24.815+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-08T05:00:24.842+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
